source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
#platform :ios, '12.0'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'HelloReactNative' do
  rn_path = '../node_modules/react-native'
  rn_darkly_path = '../node_modules/launchdarkly-react-native-client-sdk/ios/'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  #launchdarkly-react-native-client-sdk dependencies

  pod 'LaunchDarkly', '4.1.0'

  pod 'LaunchdarklyReactNativeClient', path: rn_darkly_path

  use_native_modules!
end
